
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {

    @Test
    public void testRoll() {
        int[] rolls = Library.roll(4);
        assertEquals(4, rolls.length);
        for (int roll : rolls) {
            assertTrue(roll >= 1 && roll <= 6);
        }
    }

    @Test
    public void testContainsDuplicates() {
        int[] arrayWithDuplicates = {1, 2, 3, 4, 2};
        assertTrue(Library.containsDuplicates(arrayWithDuplicates));

        int[] arrayWithoutDuplicates = {1, 2, 3, 4, 5};
        assertFalse(Library.containsDuplicates(arrayWithoutDuplicates));
    }

    @Test
    public void testCalculateAverage() {
        int[] array = {3, 5, 7, 10, 2};
        double expectedAverage = (3 + 5 + 7 + 10 + 2) / 5.0;
        assertEquals(expectedAverage, Library.calculateAverage(array));
    }

    @Test
    public void testFindArrayWithLowestAverage() {
        int[][] arrays = {
                {2, 4, 6, 8},
                {1, 3, 5, 7},
                {10, 20, 30, 40}
        };
        int[] expectedLowestAverageArray = {1, 3, 5, 7};
        assertArrayEquals(expectedLowestAverageArray, Library.findArrayWithLowestAverage(arrays));
    }
}
