
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Library {
    public static int[] roll(int n) {
        int[] rolls = new int[n];
        for (int i = 0; i < n; i++) {
            rolls[i] = (int) (Math.random() * 6) + 1;
        }
        return rolls;
    }

    public static boolean containsDuplicates(int[] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = i + 1; j < array.length; j++) {
                if (array[i] == array[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static double calculateAverage(int[] array) {
        if (array.length == 0) {
            throw new IllegalArgumentException("Array is empty.");
        }
        int sum = 0;
        for (int num : array) {
            sum += num;
        }
        return (double) sum / array.length;
    }

    public static int[] findArrayWithLowestAverage(int[][] arrays) {
        if (arrays.length == 0) {
            throw new IllegalArgumentException("Arrays is empty.");
        }
        int minIndex = 0;
        double minAverage = Double.MAX_VALUE;

        for (int i = 0; i < arrays.length; i++) {
            double average = calculateAverage(arrays[i]);
            if (average < minAverage) {
                minAverage = average;
                minIndex = i;
            }
        }

        return arrays[minIndex];
    }

    public static void main(String[] args) {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int[] lowestAverageArray = findArrayWithLowestAverage(weeklyMonthTemperatures);
        System.out.println("Array with lowest average: " + Arrays.toString(lowestAverageArray));
    }
}