/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static  void main (){

        Restaurant restaurant= new Restaurant("yasmeen",0,"$$");
        Review review1=new Review("is very good","ali",4);
        Review review2=new Review("not bad","arwa",3);
        restaurant.addReview(review1);
        restaurant.addReview(review2);
        System.out.println("Restaurant Information:");
        System.out.println(restaurant);
        restaurant.getReviews();



    }

}
